name: Deploy to Github Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Fetch README files
        run: bash build.sh

      - name: Build page
        run: hugo --minify

      - name: Deploy page to branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
